version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4
  aws-cli: circleci/aws-cli@0.1.4

defaults: &defaults
  docker:
    - image: circleci/python:3.6
jobs:
  deploy-development:
    <<: *defaults
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_SECRET_ACCESS_KEY
          aws-secret-access-key: AWS_DEFAULT_REGION
          profile-name: 'default'
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          profile-name: 'default'
          account-url: ECR_ACCOUNT_URL
          repo: 'coa-notificationsapi'
          extra-build-args: '--build-arg sessionName=${SESSION_NAME}/
                     --build-arg sessionSecret=${SESSION_SECRET}/
                     --build-arg maxSessionDays=${MAX_SESSION_DAYS}/
                     --build-arg cache_method=${CACHE_METHOD}/
                     --build-arg region=${AWS_DEFAULT_REGION}/
                     --build-arg userpoolId=${USER_POOL_ID}/
                     --build-arg appClientId=${APP_CLIENT_ID}/
                     --build-arg cognitoOauthUrl=${COGNITO_OAUTH_URL}/
                     --build-arg mds_host=${MDS_HOST}/
                     --build-arg mds_user=${MDS_USER}/
                     --build-arg mds_password=${MDS_PASSWORD}/
                     --build-arg mds_database=${MDS_DATABASE}/
                     --build-arg note_host=${NOTE_HOST}
                     --build-arg note_user=${NOTE_USER}/
                     --build-arg note_password=${NOTE_PASSWORD}/
                     --build-arg note_database=${NOTE_DATABASE}'
          tag: '${CIRCLE_SHA1}'


workflows:
  build-deploy:
    jobs:
      - deploy-development:
          filters:
            branches:
              only: development
          context: development

