version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4

defaults: &defaults
  docker:
    - image: circleci/python:3.6
jobs:
  deploy-production:
    <<: *defaults
    steps:
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: 'coa-notificationsapi'
          extra-build-args: '--build-arg sessionName=${SESSION_NAME}/
                     --build-arg sessionSecret=${SESSION_SECRET}/
                     --build-arg maxSessionDays=${MAX_SESSION_DAYS}/
                     --build-arg cache_method=${CACHE_METHOD}/
                     --build-arg region=${AWS_DEFAULT_REGION}/
                     --build-arg userpoolId=${USER_POOL_ID}/
                     --build-arg appClientId=${APP_CLIENT_ID}/
                     --build-arg cognitoOauthUrl=${COGNITO_OAUTH_URL}/
                     --build-arg mds_host=${MDS_HOST}/
                     --build-arg mds_user=${MDS_USER}/
                     --build-arg mds_password=${MDS_PASSWORD}/
                     --build-arg mds_database=${MDS_DATABASE}/
                     --build-arg note_host=${NOTE_HOST}
                     --build-arg note_user=${NOTE_USER}/
                     --build-arg note_password=${NOTE_PASSWORD}/
                     --build-arg note_database=${NOTE_DATABASE}
                     --build-arg AWS_PROFILE=${AWS_PROFILE}
                     --build-arg EMAIL_SENDER=${EMAIL_SENDER}
                     --build_arg emailhashkey=${EMAIL_HASHKEY}
                     --build-arg unsubURL=${UNSUB_URL}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/update-service:
          family: 'notifyapi'
          cluster-name: 'notifyapi_ecs_cluster'
          service-name: 'notifyapi'
          container-image-name-updates: 'container=notifyapi,tag=${CIRCLE_SHA1}'
          force-new-deployment: true
          verify-revision-is-deployed: true
          max-poll-attempts: 30
          poll-interval: 60
          fail-on-verification-timeout: false
  deploy-development:
    <<: *defaults
    steps:
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: 'coa-notificationsapi'
          extra-build-args: '--build-arg sessionName=${SESSION_NAME}/
                     --build-arg sessionSecret=${SESSION_SECRET}/
                     --build-arg maxSessionDays=${MAX_SESSION_DAYS}/
                     --build-arg cache_method=${CACHE_METHOD}/
                     --build-arg region=${AWS_DEFAULT_REGION}/
                     --build-arg userpoolId=${USER_POOL_ID}/
                     --build-arg appClientId=${APP_CLIENT_ID}/
                     --build-arg cognitoOauthUrl=${COGNITO_OAUTH_URL}/
                     --build-arg mds_host=${MDS_HOST}/
                     --build-arg mds_user=${MDS_USER}/
                     --build-arg mds_password=${MDS_PASSWORD}/
                     --build-arg mds_database=${MDS_DATABASE}/
                     --build-arg note_host=${NOTE_HOST}
                     --build-arg note_user=${NOTE_USER}/
                     --build-arg note_password=${NOTE_PASSWORD}/
                     --build-arg note_database=${NOTE_DATABASE}'
          tag: '${CIRCLE_SHA1}'
            
      - aws-ecs/update-service:
          family: 'notifyapi'
          cluster-name: 'notifyapi_ecs_cluster'
          service-name: 'notifyapi'
          container-image-name-updates: 'container=notifyapi,tag=${CIRCLE_SHA1}'
          force-new-deployment: true
          verify-revision-is-deployed: true
          max-poll-attempts: 30
          poll-interval: 60
          fail-on-verification-timeout: false


workflows:
  build-deploy:
    jobs:
      - deploy-development:
          filters:
            branches:
              only: development
          context: notifications-development

      - deploy-production:
          filters:
            branches:
              only:  master
          context: notifications-production
          type: approval
