version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - deploy:
          name: push to ec2
          command: ssh -o "StrictHostKeyChecking no" circleci@$SERVER_HOSTNAME "cd /opt/coa-converse-api; git pull; npm ci; cd deployment; sh redeploy.sh;"

workflows:
  version: 2
  deploy-dev:
    jobs:
      - build:
          filters:
            branches:
              only: development
          context: dev-converse-api
