/* **************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the graphql-starter-template repository.
  Changes made to this file inside child repos will NOT be reflected in the parent source
  template repository, and will interfere with the ability to upgrade common code from
  the template repository.
***************************************************************************************** */
const Logger = require('coa-node-logging');

const logFile = process.env.logfile ? process.env.logfile : null;
const loggerName = process.env.loggerName ? process.env.loggerName : 'webapp';
const logger = new Logger(loggerName, logFile);

module.exports = logger;
