query GetMsg {
  message(id: 1){
    message
    topic {
      name
      tags {
        name
        category {
          name
        }
      }
    }
  }
}

query GetUserPreferences {
  UserPreferences {
    id
    location_x
    location_y
    subscriptions {
      radius_miles
    }
    send_types {
      type 
      email
    }
  }

}

query GetTag {
  tag(id: 1) {
    name
    category {
      name
    }
    subscribers {
      send_types {
        type 
        email
      }
    }
    topics {
      name
      messages {
        message
      }
    }
  }
  
}

query Topics {
  topics {
    id
    name
  }
}

mutation createTopic($topicname: String!) {
  createTopic(name: $topicname) {
    id
    name
  }
}
mutation deleteTopic($delid: ID!) {
  deleteTopic(id: $delid) {
    id
    name
  }
}

query Tags {
  tags {
    id
    name
  }
}

mutation createTag($tag: TagInput!) {
  createTag(tag: $tag) {
    id
    name
		category {
      name
    }
  }
}

mutation deleteTag($delid: ID!) {
  deleteTag(id: $delid) {
    id
    name
  }
}

{
   "tag": {
    "name": "bob",
    "category": "1"
  },
 "delid": "5"
}



